Repository rticommunity/rtiperftest, pull requests merged in 2018-05, with the labels that each got.

#60 Unreliable behavior when using Best Effort + Scan in certain architectures (#59)
  srcCpp/MessagingIF.h
  srcCpp/RTIDDSImpl.cxx
  srcCpp/RTIDDSImpl.h
  srcCpp/perftest_publisher.cxx
  srcCpp03/MessagingIF.h
  srcCpp03/RTIDDSImpl.cxx
  srcCpp03/RTIDDSImpl.h
  srcCpp03/perftest_publisher.cxx
  srcCs/MessagingIF.cs
  srcCs/RTIDDSImpl.cs
  srcCs/perftest_publisher.cs
  srcDoc/compilation.rst
  srcDoc/release_notes.rst
  srcJava/com/rti/perftest/IMessagingWriter.java
  srcJava/com/rti/perftest/ddsimpl/RTIPublisher.java
  srcJava/com/rti/perftest/harness/AnnouncementListener.java
  srcJava/com/rti/perftest/harness/PerfTest.java
Labels: bug

#68 Fix Warnings (#64)
  srcCpp/MessagingIF.h
  srcCpp/RTIDDSImpl.cxx
  srcCpp/perftest_publisher.cxx
Labels: warning

#71 Maximum Latency is not correctly obtained when the clock has low resolution
  srcCpp/perftest_cpp.h
  srcCpp/perftest_publisher.cxx
  srcCpp03/perftest_cpp.h
  srcCpp03/perftest_publisher.cxx
  srcCs/perftest_publisher.cs
  srcDoc/release_notes.rst
  srcJava/com/rti/perftest/harness/LatencyListener.java
  srcJava/com/rti/perftest/harness/PerfTest.java
Labels: bug

#62 Feature/54 dds and perftest print versions
  srcCpp/perftest_cpp.h
  srcCpp/perftest_publisher.cxx
  srcCpp03/perftest_cpp.h
  srcCpp03/perftest_publisher.cxx
  srcCs/perftest_publisher.cs
  srcDoc/release_notes.rst
  srcJava/com/rti/perftest/ddsimpl/PerftestVersion.java
  srcJava/com/rti/perftest/harness/PerfTest.java
Labels: feature

#66 Feature/55 review dynamic data
  srcCpp/RTIDDSImpl.cxx
  srcCpp/RTIDDSImpl.h
  srcCpp03/RTIDDSImpl.cxx
  srcCpp03/RTIDDSImpl.h
  srcCs/perftest_publisher.cs
  srcDoc/release_notes.rst
  srcJava/com/rti/perftest/ddsimpl/DynamicDataMembersId.java
  srcJava/com/rti/perftest/ddsimpl/DynamicDataTypeHelper.java
Labels: refactoring

#82 Reduce memory consumption in the subscriber side
  perftest_qos_profiles.xml
  srcCpp/MessagingIF.h
  srcCpp/RTIDDSImpl.cxx
  srcCpp/RTIDDSImpl.h
  srcCpp/perftest_publisher.cxx
  srcCpp03/MessagingIF.h
  srcCpp03/RTIDDSImpl.cxx
  srcCpp03/RTIDDSImpl.h
  srcCpp03/perftest_publisher.cxx
  srcCs/MessagingIF.cs
  srcCs/RTIDDSImpl.cs
  srcCs/perftest_publisher.cs
  srcDoc/release_notes.rst
  srcJava/com/rti/perftest/IMessaging.java
  srcJava/com/rti/perftest/ddsimpl/RTIDDSImpl.java
  srcJava/com/rti/perftest/harness/PerfTest.java
Labels: enhancement

#56 Feature/44 warning multicast
  srcCpp/PerftestTransport.cxx
  srcCpp/PerftestTransport.h
  srcCpp/RTIDDSImpl.cxx
  srcCpp/RTIDDSImpl.h
  srcCpp/perftest_cpp.h
  srcCpp/perftest_publisher.cxx
  srcCpp03/PerftestTransport.cxx
  srcCpp03/PerftestTransport.h
  srcCpp03/RTIDDSImpl.cxx
  srcCpp03/RTIDDSImpl.h
  srcCpp03/perftest_cpp.h
  srcCpp03/perftest_publisher.cxx
  srcCs/PerftestTransport.cs
  srcCs/RTIDDSImpl.cs
  srcCs/perftest_publisher.cs
  srcDoc/command_line_parameters.rst
  srcDoc/release_notes.rst
  srcIdl/perftest.idl
  srcJava/com/rti/perftest/ddsimpl/PerftestTransport.java
  srcJava/com/rti/perftest/ddsimpl/RTIDDSImpl.java
  srcJava/com/rti/perftest/harness/PerfTest.java
Labels: enhancement
